import { defaultSchema } from 'rehype-sanitize';

export const markdownSanitizeSchema = {
  ...defaultSchema,
  // Heading IDs are generated by MarkView and used by the table of contents.
  clobberPrefix: '',
  tagNames: [...(defaultSchema.tagNames ?? []), 'kbd'],
};
