import { defaultSchema } from 'rehype-sanitize';

export const markdownSanitizeSchema = {
  ...defaultSchema,
  // Heading IDs are generated by MarkView and used by the table of contents.
  clobberPrefix: '',
  tagNames: [...(defaultSchema.tagNames ?? []), 'kbd'],
  // The default schema allows only http/https for `src`, which silently drops
  // inline base64 images. MarkdownView deliberately passes `data:` URLs through
  // untouched, and an image loaded from a data URL cannot execute script.
  protocols: {
    ...defaultSchema.protocols,
    src: [...(defaultSchema.protocols?.src ?? []), 'data'],
  },
};
